let
    Source = Json.Document(Web.Contents("https://api.airtable.com/v0/appZ9WEKw4oyxzs4p/CIF%20Form?api_key=keyXI6vFpFtKHONB0")),
    records = Source[records],
    #"Converted to Table1" = Table.FromList(records, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table1", "Column1", {"id", "fields", "createdTime"}, {"Column1.id", "Column1.fields", "Column1.createdTime"}),
    #"Expanded Column1.fields" = Table.ExpandRecordColumn(#"Expanded Column1", "Column1.fields", {"age division", "Animal/animal_bite", "animal/animal_bite/day", "animal/animal_bite/dontknow", "animal/animal_bite/month", "animal/animal_bite/never", "animal/animal_bite/week", "Animal/bird_droppings", "Animal/birds", "Animal/dead_birds", "Animal/farm_rural_time", "Animal/horses", "Animal/hunting", "Animal/insect_bite", "Animal/mosquito_bite", "Animal/pigs", "Animal/rodent_droppings", "Animal/rodent_type", "Animal/rodents", "Behaviors/hh_bed_nets", "Behaviors/hh_bug_spray", "Behaviors/hh_burn_citronella", "Behaviors/hh_clean_debris", "Behaviors/hh_clean_debris_freq", "Behaviors/hh_cover_water", "Behaviors/hh_eliminate_stag_water", "Behaviors/hh_eliminate_stag_water_freq", "Behaviors/hh_openings_closed", "Behaviors/hh_openings_closed_freq", "Behaviors/hh_spray_insecticide", "Behaviors/spoken_control_mosq", "Check/consent_filed", "Check/follow_up_appointment", "Check/follow_up_label", "Check/malaria", "Check/nasal", "Check/purple_top", "Check/red_top", "Check/sample_list", "Check/samples_lab", "Check/throat", "Checkpoint", "Checkpoints", "CP/centrifuge", "CP/package", "CP/sent_for_deliv", "CP/Visits", "Discharge/disposition", "end", "Evaluation/blood_pressure_dia", "Evaluation/blood_pressure_sys", "Evaluation/capillary_refill", "Evaluation/date_time", "Evaluation/heart_rate", "Evaluation/respiratory_rate", "Evaluation/temperature", "Evaluation/weight", "Field 428", "Infection/another_mosq_disease", "Job/farmer/chickens", "Job/farmer/cows", "Job/farmer/fruit", "Job/farmer/goats", "Job/farmer/other", "Job/farmer/pigs", "Job/farmer/sheep", "Job/farmer/sugar_cane", "Job/farmer/vegetables_roo", "Job/occupation", "Knowledge/chikungunya_infect", "Knowledge/chikungunya_know", "Knowledge/chikungunya_spread", "Knowledge/chikungunya_symptoms", "Knowledge/dengue_infect", "Knowledge/dengue_know", "Knowledge/dengue_spread", "Knowledge/dengue_symptoms", "Knowledge/health_information", "Knowledge/health_information copy", "Knowledge/lepto_infect", "Knowledge/lepto_know", "Knowledge/lepto_spread", "Knowledge/lepto_symptoms", "Knowledge/zika_infect", "Knowledge/zika_know", "Knowledge/zika_spread", "Knowledge/zika_symptoms", "Lab Reception Form", "lab sample count", "Moca", "municipality", "Perceptions/concerned/chikungunya_family", "Perceptions/concerned/chikungunya_you", "Perceptions/concerned/dengue_family", "Perceptions/concerned/dengue_you", "Perceptions/concerned/diabetes_family", "Perceptions/concerned/diabetes_you", "Perceptions/concerned/heart_attack_family", "Perceptions/concerned/heart_attack_you", "Perceptions/concerned/lepto_family", "Perceptions/concerned/lepto_you", "Perceptions/concerned/stroke_family", "Perceptions/concerned/stroke_you", "Perceptions/concerned/zika_family", "Perceptions/concerned/zika_you", "Perceptions/control_mosq_responsibilty", "Perceptions/mosq_prevent_barriers", "Perceptions/useful_prevent_mosq", "PI/ac", "PI/ac_in_house", "PI/address_length", "PI/age_calc", "PI/barcode", "PI/barrio", "PI/barrio_home", "PI/born_in_DR", "PI/child1_age", "PI/children", "PI/education", "PI/enrolled", "PI/ethnicity", "PI/floor_material", "PI/home_setting", "PI/home_water_supply", "PI/home_water_supply/reticulated___", "PI/home_water_supply/water_pump", "PI/house_screens", "PI/inpatient_admit_date", "PI/location", "PI/municipality", "PI/nbr_children", "PI/nbr_people_household", "PI/province", "PI/sex", "PI/so_name", "PI/vehicle_ownership", "PI/wall/concrete", "PI/wall/Stone", "PI/wall/wood", "PI/wall_material", "PI_barcode", "Preg/pregnant_length", "Preg/pregnant_months", "Preg/pregnant_yn", "Rec/construction", "Rec/garden", "Rec/spend_time", "Rec/unused_space", "Rec/water_exposures", "Rec/water_type", "San Pedro", "start", "sym/abdominal", "sym/blood_stool", "sym/blue_lips", "sym/calf_pain", "sym/chills", "sym/cough", "sym/decreased_urin", "sym/diarrhea", "sym/disoriented", "sym/dizzy", "sym/eye_pain", "sym/headache", "sym/itchy_skin", "sym/joint_pain", "sym/malaise", "sym/muscle pain", "sym/nausea", "sym/neck_pain", "sym/no_appetite", "sym/nose_bleeding", "sym/red_eyes", "sym/red_rash", "sym/red_swollen_joints", "sym/runny_nose", "sym/seizures", "sym/swollen_hands_feet", "sym/throat", "sym/vomiting", "sym/yellow_skin", "Symptoms/admitted_hospital_8weeks", "Symptoms/antibiotics_treat", "Symptoms/chronic_disease", "Symptoms/date_fever", "Symptoms/date_symptom", "Symptoms/fever_today", "Symptoms/rx/abdominal_pain", "Symptoms/rx/blood_stool", "Symptoms/rx/blue_lips_skin", "Symptoms/rx/calf_pain", "Symptoms/rx/chills", "Symptoms/rx/cough", "Symptoms/rx/decreased_urine", "Symptoms/rx/diarrhea", "Symptoms/rx/disoriented", "Symptoms/rx/eye_pain", "Symptoms/rx/feel_dizzy", "Symptoms/rx/headache", "Symptoms/rx/itchy_skin", "Symptoms/rx/joint_pain", "Symptoms/rx/malaise", "Symptoms/rx/muscle_pain", "Symptoms/rx/nausea", "Symptoms/rx/neck_pain", "Symptoms/rx/no_appetite", "Symptoms/rx/nose_bleeding", "Symptoms/rx/red_eyes", "Symptoms/rx/red_rash", "Symptoms/rx/red_swollen_joints", "Symptoms/rx/runny_nose", "Symptoms/rx/seizures", "Symptoms/rx/swollen_hands_feet", "Symptoms/rx/throat_pain", "Symptoms/rx/vomiting", "Symptoms/rx/yellow_skin_eyes", "today", "Travel/outside_DR", "Travel/outside_province", "Travel/provinces_traveled", "Visit", "Visit/1"}, {"Column1.fields.age division", "Column1.fields.Animal/animal_bite", "Column1.fields.animal/animal_bite/day", "Column1.fields.animal/animal_bite/dontknow", "Column1.fields.animal/animal_bite/month", "Column1.fields.animal/animal_bite/never", "Column1.fields.animal/animal_bite/week", "Column1.fields.Animal/bird_droppings", "Column1.fields.Animal/birds", "Column1.fields.Animal/dead_birds", "Column1.fields.Animal/farm_rural_time", "Column1.fields.Animal/horses", "Column1.fields.Animal/hunting", "Column1.fields.Animal/insect_bite", "Column1.fields.Animal/mosquito_bite", "Column1.fields.Animal/pigs", "Column1.fields.Animal/rodent_droppings", "Column1.fields.Animal/rodent_type", "Column1.fields.Animal/rodents", "Column1.fields.Behaviors/hh_bed_nets", "Column1.fields.Behaviors/hh_bug_spray", "Column1.fields.Behaviors/hh_burn_citronella", "Column1.fields.Behaviors/hh_clean_debris", "Column1.fields.Behaviors/hh_clean_debris_freq", "Column1.fields.Behaviors/hh_cover_water", "Column1.fields.Behaviors/hh_eliminate_stag_water", "Column1.fields.Behaviors/hh_eliminate_stag_water_freq", "Column1.fields.Behaviors/hh_openings_closed", "Column1.fields.Behaviors/hh_openings_closed_freq", "Column1.fields.Behaviors/hh_spray_insecticide", "Column1.fields.Behaviors/spoken_control_mosq", "Column1.fields.Check/consent_filed", "Column1.fields.Check/follow_up_appointment", "Column1.fields.Check/follow_up_label", "Column1.fields.Check/malaria", "Column1.fields.Check/nasal", "Column1.fields.Check/purple_top", "Column1.fields.Check/red_top", "Column1.fields.Check/sample_list", "Column1.fields.Check/samples_lab", "Column1.fields.Check/throat", "Column1.fields.Checkpoint", "Column1.fields.Checkpoints", "Column1.fields.CP/centrifuge", "Column1.fields.CP/package", "Column1.fields.CP/sent_for_deliv", "Column1.fields.CP/Visits", "Column1.fields.Discharge/disposition", "Column1.fields.end", "Column1.fields.Evaluation/blood_pressure_dia", "Column1.fields.Evaluation/blood_pressure_sys", "Column1.fields.Evaluation/capillary_refill", "Column1.fields.Evaluation/date_time", "Column1.fields.Evaluation/heart_rate", "Column1.fields.Evaluation/respiratory_rate", "Column1.fields.Evaluation/temperature", "Column1.fields.Evaluation/weight", "Column1.fields.Field 428", "Column1.fields.Infection/another_mosq_disease", "Column1.fields.Job/farmer/chickens", "Column1.fields.Job/farmer/cows", "Column1.fields.Job/farmer/fruit", "Column1.fields.Job/farmer/goats", "Column1.fields.Job/farmer/other", "Column1.fields.Job/farmer/pigs", "Column1.fields.Job/farmer/sheep", "Column1.fields.Job/farmer/sugar_cane", "Column1.fields.Job/farmer/vegetables_roo", "Column1.fields.Job/occupation", "Column1.fields.Knowledge/chikungunya_infect", "Column1.fields.Knowledge/chikungunya_know", "Column1.fields.Knowledge/chikungunya_spread", "Column1.fields.Knowledge/chikungunya_symptoms", "Column1.fields.Knowledge/dengue_infect", "Column1.fields.Knowledge/dengue_know", "Column1.fields.Knowledge/dengue_spread", "Column1.fields.Knowledge/dengue_symptoms", "Column1.fields.Knowledge/health_information", "Column1.fields.Knowledge/health_information copy", "Column1.fields.Knowledge/lepto_infect", "Column1.fields.Knowledge/lepto_know", "Column1.fields.Knowledge/lepto_spread", "Column1.fields.Knowledge/lepto_symptoms", "Column1.fields.Knowledge/zika_infect", "Column1.fields.Knowledge/zika_know", "Column1.fields.Knowledge/zika_spread", "Column1.fields.Knowledge/zika_symptoms", "Column1.fields.Lab Reception Form", "Column1.fields.lab sample count", "Column1.fields.Moca", "Column1.fields.municipality", "Column1.fields.Perceptions/concerned/chikungunya_family", "Column1.fields.Perceptions/concerned/chikungunya_you", "Column1.fields.Perceptions/concerned/dengue_family", "Column1.fields.Perceptions/concerned/dengue_you", "Column1.fields.Perceptions/concerned/diabetes_family", "Column1.fields.Perceptions/concerned/diabetes_you", "Column1.fields.Perceptions/concerned/heart_attack_family", "Column1.fields.Perceptions/concerned/heart_attack_you", "Column1.fields.Perceptions/concerned/lepto_family", "Column1.fields.Perceptions/concerned/lepto_you", "Column1.fields.Perceptions/concerned/stroke_family", "Column1.fields.Perceptions/concerned/stroke_you", "Column1.fields.Perceptions/concerned/zika_family", "Column1.fields.Perceptions/concerned/zika_you", "Column1.fields.Perceptions/control_mosq_responsibilty", "Column1.fields.Perceptions/mosq_prevent_barriers", "Column1.fields.Perceptions/useful_prevent_mosq", "Column1.fields.PI/ac", "Column1.fields.PI/ac_in_house", "Column1.fields.PI/address_length", "Column1.fields.PI/age_calc", "Column1.fields.PI/barcode", "Column1.fields.PI/barrio", "Column1.fields.PI/barrio_home", "Column1.fields.PI/born_in_DR", "Column1.fields.PI/child1_age", "Column1.fields.PI/children", "Column1.fields.PI/education", "Column1.fields.PI/enrolled", "Column1.fields.PI/ethnicity", "Column1.fields.PI/floor_material", "Column1.fields.PI/home_setting", "Column1.fields.PI/home_water_supply", "Column1.fields.PI/home_water_supply/reticulated___", "Column1.fields.PI/home_water_supply/water_pump", "Column1.fields.PI/house_screens", "Column1.fields.PI/inpatient_admit_date", "Column1.fields.PI/location", "Column1.fields.PI/municipality", "Column1.fields.PI/nbr_children", "Column1.fields.PI/nbr_people_household", "Column1.fields.PI/province", "Column1.fields.PI/sex", "Column1.fields.PI/so_name", "Column1.fields.PI/vehicle_ownership", "Column1.fields.PI/wall/concrete", "Column1.fields.PI/wall/Stone", "Column1.fields.PI/wall/wood", "Column1.fields.PI/wall_material", "Column1.fields.PI_barcode", "Column1.fields.Preg/pregnant_length", "Column1.fields.Preg/pregnant_months", "Column1.fields.Preg/pregnant_yn", "Column1.fields.Rec/construction", "Column1.fields.Rec/garden", "Column1.fields.Rec/spend_time", "Column1.fields.Rec/unused_space", "Column1.fields.Rec/water_exposures", "Column1.fields.Rec/water_type", "Column1.fields.San Pedro", "Column1.fields.start", "Column1.fields.sym/abdominal", "Column1.fields.sym/blood_stool", "Column1.fields.sym/blue_lips", "Column1.fields.sym/calf_pain", "Column1.fields.sym/chills", "Column1.fields.sym/cough", "Column1.fields.sym/decreased_urin", "Column1.fields.sym/diarrhea", "Column1.fields.sym/disoriented", "Column1.fields.sym/dizzy", "Column1.fields.sym/eye_pain", "Column1.fields.sym/headache", "Column1.fields.sym/itchy_skin", "Column1.fields.sym/joint_pain", "Column1.fields.sym/malaise", "Column1.fields.sym/muscle pain", "Column1.fields.sym/nausea", "Column1.fields.sym/neck_pain", "Column1.fields.sym/no_appetite", "Column1.fields.sym/nose_bleeding", "Column1.fields.sym/red_eyes", "Column1.fields.sym/red_rash", "Column1.fields.sym/red_swollen_joints", "Column1.fields.sym/runny_nose", "Column1.fields.sym/seizures", "Column1.fields.sym/swollen_hands_feet", "Column1.fields.sym/throat", "Column1.fields.sym/vomiting", "Column1.fields.sym/yellow_skin", "Column1.fields.Symptoms/admitted_hospital_8weeks", "Column1.fields.Symptoms/antibiotics_treat", "Column1.fields.Symptoms/chronic_disease", "Column1.fields.Symptoms/date_fever", "Column1.fields.Symptoms/date_symptom", "Column1.fields.Symptoms/fever_today", "Column1.fields.Symptoms/rx/abdominal_pain", "Column1.fields.Symptoms/rx/blood_stool", "Column1.fields.Symptoms/rx/blue_lips_skin", "Column1.fields.Symptoms/rx/calf_pain", "Column1.fields.Symptoms/rx/chills", "Column1.fields.Symptoms/rx/cough", "Column1.fields.Symptoms/rx/decreased_urine", "Column1.fields.Symptoms/rx/diarrhea", "Column1.fields.Symptoms/rx/disoriented", "Column1.fields.Symptoms/rx/eye_pain", "Column1.fields.Symptoms/rx/feel_dizzy", "Column1.fields.Symptoms/rx/headache", "Column1.fields.Symptoms/rx/itchy_skin", "Column1.fields.Symptoms/rx/joint_pain", "Column1.fields.Symptoms/rx/malaise", "Column1.fields.Symptoms/rx/muscle_pain", "Column1.fields.Symptoms/rx/nausea", "Column1.fields.Symptoms/rx/neck_pain", "Column1.fields.Symptoms/rx/no_appetite", "Column1.fields.Symptoms/rx/nose_bleeding", "Column1.fields.Symptoms/rx/red_eyes", "Column1.fields.Symptoms/rx/red_rash", "Column1.fields.Symptoms/rx/red_swollen_joints", "Column1.fields.Symptoms/rx/runny_nose", "Column1.fields.Symptoms/rx/seizures", "Column1.fields.Symptoms/rx/swollen_hands_feet", "Column1.fields.Symptoms/rx/throat_pain", "Column1.fields.Symptoms/rx/vomiting", "Column1.fields.Symptoms/rx/yellow_skin_eyes", "Column1.fields.today", "Column1.fields.Travel/outside_DR", "Column1.fields.Travel/outside_province", "Column1.fields.Travel/provinces_traveled", "Column1.fields.Visit", "Column1.fields.Visit/1"}),
    #"Extracted Values" = Table.TransformColumns(#"Expanded Column1.fields", {"Column1.fields.municipality", each Text.Combine(List.Transform(_, Text.From)), type text}),
    #"Changed Type" = Table.TransformColumnTypes(#"Extracted Values",{{"Column1.fields.Visit/1", Int64.Type}, {"Column1.fields.PI/age_calc", Int64.Type}, {"Column1.fields.Evaluation/blood_pressure_dia", Int64.Type}, {"Column1.fields.Evaluation/blood_pressure_sys", Int64.Type}, {"Column1.fields.Evaluation/capillary_refill", Int64.Type}, {"Column1.fields.Evaluation/heart_rate", Int64.Type}, {"Column1.fields.Evaluation/respiratory_rate", Int64.Type}, {"Column1.fields.Evaluation/temperature", type number}, {"Column1.fields.Evaluation/weight", type number}, {"Column1.fields.sym/abdominal", Int64.Type}, {"Column1.fields.sym/blood_stool", Int64.Type}, {"Column1.fields.sym/blue_lips", Int64.Type}, {"Column1.fields.sym/calf_pain", Int64.Type}, {"Column1.fields.sym/chills", Int64.Type}, {"Column1.fields.sym/cough", Int64.Type}, {"Column1.fields.sym/decreased_urin", Int64.Type}, {"Column1.fields.sym/diarrhea", Int64.Type}, {"Column1.fields.sym/disoriented", Int64.Type}, {"Column1.fields.sym/dizzy", Int64.Type}, {"Column1.fields.sym/eye_pain", Int64.Type}, {"Column1.fields.sym/headache", Int64.Type}, {"Column1.fields.sym/itchy_skin", Int64.Type}, {"Column1.fields.sym/joint_pain", Int64.Type}, {"Column1.fields.sym/malaise", Int64.Type}, {"Column1.fields.sym/muscle pain", Int64.Type}, {"Column1.fields.sym/nausea", Int64.Type}, {"Column1.fields.sym/neck_pain", Int64.Type}, {"Column1.fields.sym/no_appetite", Int64.Type}, {"Column1.fields.sym/nose_bleeding", Int64.Type}, {"Column1.fields.sym/red_eyes", Int64.Type}, {"Column1.fields.sym/red_rash", Int64.Type}, {"Column1.fields.sym/red_swollen_joints", Int64.Type}, {"Column1.fields.sym/runny_nose", Int64.Type}, {"Column1.fields.sym/seizures", Int64.Type}, {"Column1.fields.sym/swollen_hands_feet", Int64.Type}, {"Column1.fields.sym/throat", Int64.Type}, {"Column1.fields.sym/vomiting", Int64.Type}, {"Column1.fields.sym/yellow_skin", Int64.Type}, {"Column1.fields.Symptoms/admitted_hospital_8weeks", type text}, {"Column1.fields.PI/nbr_people_household", Int64.Type}, {"Column1.fields.PI/address_length", Int64.Type}, {"Column1.fields.PI/wall/concrete", Int64.Type}, {"Column1.fields.PI/wall/Stone", Int64.Type}, {"Column1.fields.PI/wall/wood", Int64.Type}, {"Column1.fields.PI/home_water_supply/reticulated___", Int64.Type}, {"Column1.fields.PI/home_water_supply/water_pump", Int64.Type}, {"Column1.fields.PI/house_screens", type text}})
in
    #"Changed Type"